const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),zlib=require('node:zlib');
const root=path.resolve(__dirname,'../../experiments/web-corp/AmountStyles/authoring'),core=require(path.resolve(__dirname,'../../../../projects/ComponentContractEditor/dist/core.cjs'));
const compiled=require(path.join(root,'compiled/component-contract.v2.json')),manual=require(path.join(root,'contract.manual.json')),runtime=core.prepareAuthoringPreviewContract(compiled);
const id='component:web-corp.amount-styles.manual-interactive-decoration-is-forbidden';
const fixture=()=>JSON.parse(zlib.gunzipSync(fs.readFileSync(path.join(root,'reports/fixtures/r8-editor-0.2.63/amount-styles.validation-report.2026-09-30T06-30-28-788Z.json.gz')))).snapshot;
const check=s=>core.evaluateCompiledContract(s,runtime).evaluations.filter(e=>e.ruleId.startsWith(id+'.'));
const failures=s=>check(s).filter(e=>['violation','human-review'].includes(e.classification));
// Synthetic capture only. Archived reports are never modified or backfilled.
function fresh(){const s=fixture();function visit(o){if(!o||typeof o!=='object')return;if(o.text&&typeof o.text.characters==='string')o.text.decoration=['NONE'];for(const v of Object.values(o))if(v&&typeof v==='object')visit(v);}visit(s);return s;}
function sync(s){for(const c of s.componentDependencyCaptures||[])for(const n of c.snapshot.nodes){const host=s.nodes.find(h=>h.id===c.nodeMap[n.id]);if(host)for(const field of ['layout','appearance','text','bounds','visible'])if(field in host)n[field]=structuredClone(host[field]);}}
test('decoration retains its stable RuleID and finite explicit target sets',()=>{const r=manual.rules.find(r=>r.id===id);assert.equal(r.execution.route,'predicate');assert.equal(r.constraints.length,3);assert(r.constraints.every(c=>c.visibleOnly&&!c.targetRoles.includes('addon')&&!c.targetRoles.includes('amount')));assert.equal(compiled.rules.filter(r=>r.ruleId.startsWith(id+'.')).length,18);assert.equal(compiled.status,'ready');});
test('old reports cannot pretend missing text decoration was checked',()=>{assert(check(fixture()).some(e=>e.classification==='human-review'));});
test('synthetic complete capture passes and does not mutate input',()=>{const s=fresh(),before=JSON.stringify(s);assert.deepEqual(failures(s),[]);assert.equal(JSON.stringify(s),before);});
for(const [index,decoration] of [[2,['UNDERLINE']],[5,['NONE','UNDERLINE']],[7,['STRIKETHROUGH']],[9,['UNDERLINE']]])test(`text ${index} decoration override and reset`,()=>{const s=fresh();s.nodes[index].text.decoration=decoration;sync(s);assert(failures(s).some(e=>e.subjectNodeId===s.nodes[index].id&&e.classification==='violation'));s.nodes[index].text.decoration=['NONE'];sync(s);assert.deepEqual(failures(s),[]);});
for(const index of [0,1,4,6,8])test(`background ${index} override and reset`,()=>{const s=fresh(),n=s.nodes[index],before=structuredClone(n.appearance.fill);n.appearance.fill=[{type:'SOLID',visible:true,opacity:1,color:'#FF0000'}];sync(s);assert(failures(s).some(e=>e.subjectNodeId===n.id&&e.classification==='violation'));n.appearance.fill=before;sync(s);assert.deepEqual(failures(s),[]);});
test('effect detail overrides are detected independently of text and fill',()=>{for(const index of [0,1,2,4,5,6,7,8,9]){const s=fresh(),n=s.nodes[index];n.appearance.effectDetailsV1=core.captureEffectDetails([{type:'LAYER_BLUR',visible:true,radius:4}],'');sync(s);assert(failures(s).some(e=>e.subjectNodeId===n.id&&e.classification==='violation'),String(index));}});
test('text paint changes and external Addon decoration are not this rule’s responsibility',()=>{const s=fresh();for(const n of s.nodes.filter(n=>n.type==='TEXT'))n.appearance.fill=[{type:'SOLID',visible:true,opacity:1,tokenId:'other-library-token'}];for(const n of s.nodes.slice(10)){n.appearance.fill=[{type:'SOLID',color:'#FF0000'}];n.appearance.effectDetailsV1=core.captureEffectDetails([{type:'LAYER_BLUR',visible:true,radius:4}],'');}sync(s);assert.deepEqual(failures(s),[]);});
test('hidden Operation skips its decoration without requiring a visible sign',()=>{const s=fresh();s.nodes[0].component.properties['Operation#57377:0']=false;s.nodes[1].visible=false;s.nodes[2].text.decoration=['UNDERLINE'];sync(s);assert.deepEqual(failures(s),[]);});
test('missing actual decoration remains human review',()=>{const s=fresh();delete s.nodes[5].text.decoration;sync(s);assert(check(s).some(e=>e.subjectNodeId==='preview:5'&&e.classification==='human-review'));});
test('missing reference decoration cannot silently exclude an assertion',()=>{const s=fresh();function remove(o){if(!o||typeof o!=='object')return;if(o.text)delete o.text.decoration;for(const v of Object.values(o))if(v&&typeof v==='object')remove(v);}remove(s);for(const n of s.nodes)if(n.type==='TEXT')n.text.decoration=['NONE'];sync(s);assert(check(s).some(e=>e.classification==='human-review'));});
test('explicit target lists reject unknown/duplicate roles and ambiguous scope settings',()=>{for(const edit of [r=>r.constraints[0].targetRoles=['not-declared'],r=>r.constraints[0].targetRoles=['root','root'],r=>r.constraints[0].visibleOnly=false,r=>r.targetScope='self-and-descendants',r=>r.boundaryPolicy='component-owned@1']){const m=structuredClone(manual);edit(m.rules.find(r=>r.id===id));assert(core.validateManualSource(m).some(i=>i.level==='error'));}});
test('structural drift never expands explicit target coverage or silently passes remapping',()=>{const s=fresh();s.nodes.push({id:'new-layer',parentId:'preview:0',childIds:[],type:'FRAME',name:'new Athena fact',visible:true,appearance:{fill:[{type:'SOLID',color:'#FF0000'}]},unknownFacts:[]});s.nodes[0].childIds.push('new-layer');const result=check(s);assert(!result.some(e=>e.subjectNodeId==='new-layer'));assert(result.some(e=>e.classification==='human-review'));assert(!result.some(e=>e.classification==='violation'));});
test('46 archived reports replay exactly and retain all unrelated verdicts',()=>{assert.equal(require('../review_amount_styles_r9').review().results.length,46);});
