const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const core=require('../../../projects/ComponentContractEditor/dist/core.cjs');
const {review:reviewLive}=require('./review_corporate_content_mobile_live');
const repo=path.resolve(__dirname,'..'),root=path.join(repo,'experiments/web-corp/CorporateContent/mobile-web/authoring');
const negativeName='corporate-content.validation-report.2026-10-01T17-59-37-209Z.json',resetName='corporate-content.validation-report.2026-10-01T18-09-18-969Z.json';
const json=file=>JSON.parse(fs.readFileSync(file)),sha=b=>crypto.createHash('sha256').update(b).digest('hex'),clone=x=>JSON.parse(JSON.stringify(x));
async function review(record=false){
 const negative=await reviewLive(negativeName,record),reset=await reviewLive(resetName,record);
 assert.equal(negative.rootNodeId,reset.rootNodeId);assert.equal(negative.reportedManualSourceHash,reset.reportedManualSourceHash);
 assert.deepEqual(negative.classifications,{compliant:15,violation:2});assert.deepEqual(reset.classifications,{compliant:17});
 assert.deepEqual(negative.observedFacts,{clipsContent:true,backgroundMode:'136941:1'});assert.deepEqual(reset.observedFacts,{clipsContent:false,backgroundMode:'136853:0'});
 assert.deepEqual(negative.violations.map(e=>e.trace.factPaths.at(-1)).sort(),['layout.clipsContent','variable.modes.22d83aeb0d0d643a5359f63464a2ab81838fbe9f']);
 const manual=json(path.join(root,'contract.manual.json')),compiled=json(path.join(root,'compiled/component-contract.v2.json')),bytes=fs.readFileSync(path.join(root,'editor/CorporateContent.mobile-web.component-contract.zip'));
 const workspace=core.importWorkspace((await core.readZip(bytes)).map(e=>({name:e.name,text:core.zipEntryText(e)})));
 assert.deepEqual(workspace.manual,manual);const bundle=core.buildExportBundle(manual,workspace.variantEvidence,workspace.dependencyContracts);
 assert.deepEqual(clone(bundle.compiled),compiled);assert.equal(compiled.status,'ready');assert.equal(bundle.validation.valid,true);
 assert.equal(manual.rules.length,6);assert.equal(compiled.rules.length,17);assert(manual.rules.every(r=>r.status==='reviewed'&&r.ownership.ownerId===manual.component.componentId));
 const ownerBytes=fs.readFileSync(path.join(repo,'experiments/current-contract-packages/CorporateContent.mobile-web.component-contract.zip'));
 const owner=core.importWorkspace((await core.readZip(ownerBytes)).map(e=>({name:e.name,text:core.zipEntryText(e)}))),normalized=clone(owner.manual);
 normalized.metadata.revision=manual.metadata.revision;normalized.metadata.updatedAt=manual.metadata.updatedAt;assert.deepEqual(normalized,manual);
 assert.equal(core.stableHash(owner.manual),reset.reportedManualSourceHash);assert.deepEqual(owner.anatomy,workspace.anatomy);
 const acceptance={schemaVersion:'apollo.component-contract.acceptance.v1',componentId:manual.component.componentId,contractId:manual.component.contractId,date:'2026-10-01',status:'accepted',scope:'figma-component',platform:'mobile-web',published:false,manualRevision:manual.metadata.revision,manualSourceHash:core.stableHash(manual),compiledHash:core.stableHash(compiled),generatedFactsHash:compiled.package.generatedFactsHash,sourceZipSha256:sha(bytes),editorVersion:'0.2.73',sourceRules:6,ruleIRCount:17,normativeSemanticsUnchanged:true,ownerAcceptance:{source:'user-message',date:'2026-10-01',quote:'всё ок'},ownerExport:{revision:owner.manual.metadata.revision,manualSourceHash:core.stableHash(owner.manual),zipSha256:sha(ownerBytes),canonicalSemanticRevision:manual.metadata.revision,normativeSemanticsUnchanged:true,preserved:true},liveEvidence:[negative,reset].map(r=>({report:r.report,fixture:r.fixture,sha256:r.reportSha256,manualRevision:r.reportedRevision,exactEngineReplay:r.exactEngineReplay,exactEditorReplay:r.exactEditorReplay,sharedCompilerReproducesReport:r.sharedCompilerReproducesReport,complete:r.coverage.complete,matchedBaselineNodes:r.matchedBaselineNodes,evaluations:r.coverage.engineEvaluations,classifications:r.classifications,observedFacts:r.observedFacts})),controlResetAcceptanceComplete:true,bodyBoundaryPolicyVerified:true,externalContentValidation:false,broaderRuleMatrixAcceptance:'Owner accepted the six declared rules after combined clipping/modal negative and page-grey reset; individual live reports for every protected capability were not supplied.',checks:{canonicalZipReopen:true,sharedCompilerReproduces:true,sourceHashesVerified:true,sourceCorrespondenceVerified:true,negativeAndResetReplay:true},limitations:['Ready covers the six authored mobile Figma rules only.','External native Body payload and its nested component contracts are outside host validation.','TopMargin/BottomMargin have no separate authored Spacer=24 checks; vertical sizing is unrestricted.','Section, page patterns, frontend parity, Code Connect and production publication are outside this acceptance.','Hub scope drift remains tracked separately in Ledger 82; no Hub normative files are rewritten.','Empty semantics.purpose remains a compiler warning.']};
 if(record){fs.writeFileSync(path.join(root,'reports/acceptance.json'),JSON.stringify(acceptance,null,2)+'\n');fs.mkdirSync(path.join(root,'runtime'),{recursive:true});fs.writeFileSync(path.join(root,'runtime/component-contract.index.json'),JSON.stringify({componentId:manual.component.componentId,contractId:manual.component.contractId,compiledPath:'../compiled/component-contract.v2.json',status:'ready',published:false,acceptedScope:'mobile-web, included-source-rules-only',manualSourceHash:acceptance.manualSourceHash,compiledHash:acceptance.compiledHash,representationKeys:manual.representations.map(r=>r.locator.componentKey)},null,2)+'\n');}
 return acceptance;
}
if(require.main===module)review(process.argv.includes('--record')).then(r=>console.log(JSON.stringify({status:r.status,manualRevision:r.manualRevision,sourceRules:r.sourceRules,checks:r.ruleIRCount,controlResetAcceptanceComplete:r.controlResetAcceptanceComplete,ownerExportPreserved:r.ownerExport.preserved}))).catch(e=>{console.error(e);process.exitCode=1;});
module.exports={review};
